packages:
  - internal/*
  - internal/lint-configs/*
  - packages/*
  - packages/@core/base/*
  - packages/@core/ui-kit/*
  - packages/@core/forward/*
  - packages/@core/*
  - packages/effects/*
  - packages/business/*
  - apps/*
  - scripts/*

catalog:
  '@ant-design/icons-vue': ^7.0.1
  '@ast-grep/napi': ^0.37.0
  '@changesets/changelog-github': ^0.5.2
  '@changesets/cli': ^2.29.8
  '@changesets/git': ^3.0.4
  '@clack/prompts': ^0.10.1
  '@codemirror/lang-json': ^6.0.2
  '@codemirror/language': ^6.11.3
  '@codemirror/legacy-modes': ^6.5.2
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@ctrl/tinycolor': ^4.2.0
  '@element-plus/icons-vue': ^2.3.2
  '@eslint/js': ^9.39.2
  '@faker-js/faker': ^9.9.0
  '@iconify/json': ^2.2.417
  '@iconify/tailwind': ^1.2.0
  '@iconify/vue': ^5.0.0
  '@intlify/core-base': ^11.2.2
  '@intlify/unplugin-vue-i18n': ^6.0.8
  '@jspm/generator': ^2.8.0
  '@manypkg/get-packages': ^2.2.2
  '@nolebase/vitepress-plugin-git-changelog': ^2.18.2
  '@playwright/test': ^1.57.0
  '@pnpm/workspace.read-manifest': ^1000.2.9
  '@stylistic/stylelint-plugin': ^3.1.3
  '@tailwindcss/nesting': 0.0.0-insiders.565cd3e
  '@tailwindcss/typography': ^0.5.19
  '@tanstack/vue-store': ^0.7.7
  '@types/archiver': ^6.0.4
  '@types/eslint': ^9.6.1
  '@types/html-minifier-terser': ^7.0.2
  '@types/json-bigint': ^1.0.4
  '@types/jsonwebtoken': ^9.0.10
  '@types/lodash.clonedeep': ^4.5.9
  '@types/lodash.get': ^4.4.9
  '@types/lodash.isequal': ^4.5.8
  '@types/lodash.set': ^4.3.9
  '@types/node': ^22.19.3
  '@types/nprogress': ^0.2.3
  '@types/postcss-import': ^14.0.3
  '@types/qrcode': ^1.5.6
  '@types/qs': ^6.14.0
  '@types/sortablejs': ^1.15.9
  '@typescript-eslint/eslint-plugin': ^8.50.0
  '@typescript-eslint/parser': ^8.50.0
  '@uiw/codemirror-theme-github': ^4.25.4
  '@vee-validate/zod': ^4.15.1
  '@vite-pwa/vitepress': ^1.1.0
  '@vitejs/plugin-vue': ^6.0.3
  '@vitejs/plugin-vue-jsx': ^5.1.2
  '@vue/reactivity': ^3.5.25
  '@vue/shared': ^3.5.25
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': ^13.9.0
  '@vueuse/integrations': ^13.9.0
  '@vueuse/motion': ^3.0.3
  '@wangeditor-next/editor': ^5.6.49
  '@wangeditor-next/editor-for-vue': ^5.1.14
  ant-design-vue: ^4.2.6
  archiver: ^7.0.1
  autoprefixer: ^10.4.23
  axios: ^1.13.2
  axios-mock-adapter: ^2.1.0
  cac: ^6.7.14
  chalk: ^5.6.2
  cheerio: ^1.1.2
  circular-dependency-scanner: ^2.3.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  commitlint-plugin-function-rules: ^4.2.0
  consola: ^3.4.2
  cross-env: ^7.0.3
  cspell: ^8.19.4
  cssnano: ^7.1.2
  cz-git: ^1.12.0
  czg: ^1.12.0
  dayjs: ^1.11.19
  defu: ^6.1.4
  depcheck: ^1.4.7
  dotenv: ^16.6.1
  echarts: ^5.6.0
  element-plus: ^2.12.0
  eslint: ^9.39.2
  eslint-config-turbo: ^2.6.3
  eslint-plugin-command: ^3.4.0
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^50.8.0
  eslint-plugin-jsonc: ^2.21.0
  eslint-plugin-n: ^17.23.1
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.1
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-regexp: ^2.10.0
  eslint-plugin-unicorn: ^59.0.1
  eslint-plugin-unused-imports: ^4.3.0
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^9.33.0
  execa: ^9.6.1
  find-up: ^7.0.0
  get-port: ^7.1.0
  globals: ^16.5.0
  h3: ^1.15.4
  happy-dom: ^17.6.3
  html-minifier-terser: ^7.2.0
  husky: ^9.1.7
  is-ci: ^4.1.0
  json-bigint: ^1.0.0
  jsonc-eslint-parser: ^2.4.2
  jsonwebtoken: ^9.0.3
  lint-staged: ^15.5.2
  lodash.clonedeep: ^4.5.0
  lodash.get: ^4.4.2
  lodash.isequal: ^4.5.0
  lodash.set: ^4.3.2
  lucide-vue-next: ^0.507.0
  medium-zoom: ^1.1.0
  naive-ui: ^2.43.2
  nitropack: ^2.12.9
  nprogress: ^0.2.0
  ora: ^8.2.0
  performant-array-to-tree: ^1.11.0
  pinia: ^3.0.4
  pinia-plugin-persistedstate: ^4.7.1
  pkg-types: ^2.3.0
  playwright: ^1.57.0
  postcss: ^8.5.6
  postcss-antd-fixes: ^0.2.0
  postcss-html: ^1.8.0
  postcss-import: ^16.1.1
  postcss-preset-env: ^10.5.0
  postcss-scss: ^4.0.9
  prettier: ^3.7.4
  prettier-plugin-tailwindcss: ^0.6.14
  publint: ^0.3.16
  qrcode: ^1.5.4
  qs: ^6.14.0
  radix-vue: ^1.9.17
  remeda: ^2.32.0
  resolve.exports: ^2.0.3
  rimraf: ^6.1.2
  rollup: ^4.53.4
  rollup-plugin-visualizer: ^5.14.0
  sass: ^1.96.0
  secure-ls: ^2.0.0
  sortablejs: ^1.15.6
  stylelint: ^16.26.1
  stylelint-config-recess-order: ^6.1.0
  stylelint-config-recommended: ^16.0.0
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^38.0.0
  stylelint-order: ^7.0.0
  stylelint-prettier: ^5.0.3
  stylelint-scss: ^6.13.0
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.19
  tailwindcss-animate: ^1.0.7
  theme-colors: ^0.1.0
  tippy.js: ^6.3.7
  turbo: ^2.6.3
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unplugin-element-plus: ^0.10.0
  vee-validate: ^4.15.1
  vite: ^7.3.0
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-pwa: ^1.2.0
  vite-plugin-vue-devtools: ^7.7.9
  vitepress: ^1.6.4
  vitepress-plugin-group-icons: ^1.6.5
  vitest: ^3.2.4
  vue: ^3.5.25
  vue-codemirror: ^6.1.1
  vue-eslint-parser: ^10.2.0
  vue-i18n: ^11.2.2
  vue-json-viewer: ^3.0.4
  vue-router: ^4.6.4
  vue-tippy: ^6.7.1
  vue-tsc: 2.1.10
  vxe-pc-ui: ^4.11.7
  vxe-table: ^4.17.30
  watermark-js-plus: ^1.6.3
  zod: ^3.25.76
  zod-defaults: ^0.1.3
  es-toolkit: ^1.43.0
  reka-ui: ^2.6.1
  lefthook: ^1.13.6
  '@tanstack/vue-query': ^5.92.1
  i18next: ^25.7.3
  zod-i18n-map: ^2.27.0
